# Generated by Django 3.2 on 2023-04-12 22:05

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230412_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(help_text='Укажите год выпуска', validators=[reviews.validators.model_validate_year], verbose_name='Год выпуска'),
        ),
    ]
