# Generated by Django 3.2 on 2023-04-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_title_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(help_text='Укажите название произведения', max_length=256, verbose_name='Названием'),
        ),
        migrations.AlterUniqueTogether(
            name='title',
            unique_together={('name', 'year')},
        ),
    ]
